### ISSUE TITLE
--select-1 hang on x64 msdos

### ISSUE THREAD

**Issue by mattn** [peco/peco#279] opened 2015-11-02 00:29 UTC
https://twitter.com/nitoyon/statuses/660832871863599104

**Comment by syohex** [comment] 2015-11-02 02:05
I can also reproduce with both released binary and binary which is built from source code.

**Comment by nitoyon** [comment] 2015-11-03 14:57
It turns out that the hangup occurs on `defer screen.Close()` in `cli.go`.  So, we have to fix termbox-go.

**Comment by nitoyon** [comment] 2015-11-04 17:00
Fixed & Sending PR https://github.com/nsf/termbox-go/pull/105

**Comment by lestrrat** [comment] 2015-11-04 21:48
MEMO: need to release peco with updated termbox dep

**Comment by lestrrat** [comment] 2016-05-11 01:35
I wonder if this has been fixed with v0.3.6?

**Closed** 2017-03-03 11:41 UTC
Labels: bug
