### ISSUE TITLE
Macports | Peco hang

### ISSUE THREAD

**Issue by cuyler** [peco/peco#255] opened 2015-07-12 17:40 UTC
When using peco in combination with Macports, peco hangs with the following:

`port installed | peco`

I'm not sure what is special about the output from port installed that causes this hang; I don't see any special characters or 'weird' line endings.

**Comment by syohex** [comment] 2015-07-13 02:14
Is this issue reproduced by following ways ?

```
% port installed > port_installed.txt
% cat port_installed.txt | peco
or
% peco port_installed.txt
```

Please upload the output file in some place, if it is reproducible.

**Comment by cuyler** [comment] 2015-07-13 02:42
Nope, works perfectly if dumped to a text file first.  It seems to be the direct pipe that's causing the problem...  I'm not super familiar with Golang or how to debug it, otherwise I would jump in and figure out what's happening.

**Comment by mattn** [comment] 2015-07-13 03:14
What do you get with below?

```
port installed | cat
```

**Comment by cuyler** [comment] 2015-07-13 04:08
List of installed ports. 

    port installed | less 

works as expected as well.

**Comment by mattn** [comment] 2015-07-13 04:12
Could you please show me the result? If you have an issue to paste on here, please send e-mail to mattn do jp at gmail.com.

**Comment by cuyler** [comment] 2015-07-13 04:45
Sure, sent an email with a screen cap demonstrating the problem.

**Comment by lestrrat** [comment] 2015-07-13 05:09
Okay, I saw the movie. Didn't help much, sorry.
How about this: Reproduce the hang, then send a SIGABRT to the peco process, and send us the complete stacktrace?

**Comment by cuyler** [comment] 2015-07-13 06:08
No worries, thanks for digging in.. Here's the SIGABRT dump.. I formatted it for easier reading:

SIGABRT: abort
PC=0x3ccfb

goroutine 0 [idle]:
	runtime.mach_semaphore_wait(0x803, 0x0, 0x22083d55f0, 0x22083d55f0, 0x2b674, 0x208490000, 0x2000, 0x39f0a, 0x2de70, 0x7fff5fbff428, ...)
                                                                                               /opt/local/go/src/runtime/sys_darwin_amd64.s:412 +0xb
 	semasleep()
	
/opt/local/go/src/runtime/os_darwin.c:438 +0x16c
	runtime.onM(0x7fff5fbff428)

/opt/local/go/src/runtime/asm_amd64.s:273 +0x9a
	runtime.semasleep(0xffffffffffffffff, 0x0)

/opt/local/go/src/runtime/os_darwin.c:457 +0x60
	runtime.notesleep(0x368958)

/opt/local/go/src/runtime/lock_sema.go:171 +0x114
	stopm()
	
/opt/local/go/src/runtime/proc.c:1178 +0x119
	findrunnable(0x2083e0000)

/opt/local/go/src/runtime/proc.c:1487 +0x562
	schedule()

/opt/local/go/src/runtime/proc.c:1575 +0x151
	runtime.park_m(0x2083cf8c0)
                                                                     	
/opt/local/go/src/runtime/proc.c:1654 +0x113
	runtime.mcall(0x30504)
                	
/opt/local/go/src/runtime/asm_amd64.s:186 +0x5a
	goroutine 1 [semacquire]:
		sync.(*WaitGroup).Wait(0x2083ec6e0)
         	
/opt/local/go/src/sync/waitgroup.go:132 +0x169
	github.com/peco/peco.(*Ctx).WaitDone(0x2083cf0e0)

/work/src/github.com/peco/peco/ctx.go:256 +0x2f
	github.com/peco/peco.(*CLI).Run(0x20842df10, 0x0, 0x0)

/work/src/github.com/peco/peco/cli.go:226 +0xc86
	main._main(0x24a1)

/work/src/github.com/peco/peco/cmd/peco/peco.go:27 +0x79
	main.main()

/work/src/github.com/peco/peco/cmd/peco/peco.go:18 +0x35
	goroutine 5 [syscall]:
    	os/signal.loop()

/opt/local/go/src/os/signal/signal_unix.go:21 +0x1f
	created by os/signal.init·1

/opt/local/go/src/os/signal/signal_unix.go:27 +0x35
	goroutine 6 [chan send]:
		github.com/peco/peco.func·034()

/work/src/github.com/peco/peco/line.go:19 +0x56
	created by github.com/peco/peco.newIDGen

/work/src/github.com/peco/peco/line.go:24 +0xb5
	goroutine 9 [select]:
		github.com/nsf/termbox-go.func·001()

/work/src/github.com/nsf/termbox-go/api.go:87 +0x43b
	created by github.com/nsf/termbox-go.Init

/work/src/github.com/nsf/termbox-go/api.go:106 +0x951
	goroutine 10 [select]:
		github.com/peco/peco.(*Input).Loop(0x208406000)

/work/src/github.com/peco/peco/input.go:29 +0x207
	created by github.com/peco/peco.(*Ctx).startInput

/work/src/github.com/peco/peco/ctx.go:454 +0x57
	goroutine 11 [select]:
		github.com/peco/peco.(*View).Loop(0x20847c840)

/work/src/github.com/peco/peco/view.go:41 +0x5a5
	created by github.com/peco/peco.(*CLI).Run

/work/src/github.com/peco/peco/cli.go:216 +0xbe3
	goroutine 12 [select]:
    	github.com/peco/peco.(*Filter).Loop(0x208488080)

/work/src/github.com/peco/peco/filter.go:182 +0x1f4
	created by github.com/peco/peco.(*CLI).Run

/work/src/github.com/peco/peco/cli.go:216 +0xbe3
	goroutine 13 [select]:
		github.com/peco/peco.(*signalHandler).Loop(0x208486600)

/work/src/github.com/peco/peco/ctx.go:380 +0x17e
	created by github.com/peco/peco.(*CLI).Run

/work/src/github.com/peco/peco/cli.go:216 +0xbe3
	goroutine 18 [select]:
		github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)

/work/src/github.com/nsf/termbox-go/api.go:321 +0x63f
	github.com/peco/peco.func·045()

/work/src/github.com/peco/peco/screen.go:54 +0xa3
	created by github.com/peco/peco.Termbox.PollEvent

/work/src/github.com/peco/peco/screen.go:56 +0xb5

rax     0xe
rbx     0x368880
rcx     0x7fff5fbff3d0
rdx     0x7fff5fbff428
rdi     0x803
rsi     0x10
rbp     0x1
rsp     0x7fff5fbff3d0
r8      0x35cc199
r9      0x1
r10     0x937e931f6
r11     0x286
r12     0x0
r13     0x38fe159b46c70
r14     0x13f06baea6e9a600
r15     0x10
rip     0x3ccfb
rflags  0x286
cs      0x7
fs      0x0
gs      0x0

**Comment by cuyler** [comment] 2015-07-13 06:11
Also, FWIW, this happens on both 0.3.2 and 0.3.3.

**Comment by lestrrat** [comment] 2015-07-13 06:21
Hmmmmmmm, at first sight nothing seems to jump out. seemingly everything is fine and ready...
This is going to take some time to debug, I'm afraid.

**Comment by cuyler** [comment] 2015-07-13 06:24
No problem, it ONLY happens with that command combo ( that I've found ).. If there's some way I can help debug, let me know... I'm an Erlang/C/Lua programmer not a golang programmer so I may not be of much use but willing to help out if I can.

Regardless, thanks for peco, I use it many times per day, makes my life much easier.

**Comment by syohex** [comment] 2015-07-13 06:33
@cuyler Which go version do you use ?

**Comment by cuyler** [comment] 2015-07-13 06:37
I was using 0.3.2; I updated to 0.3.3 ( from distributions ) but the problem persisted.

**Comment by syohex** [comment] 2015-07-13 06:39
> I was using 0.3.2; I updated to 0.3.3 ( from distributions ) but the problem persisted.

Not peco version, Please tell us golang version.

**Comment by syohex** [comment] 2015-07-13 12:28
Ah, sorry you use binary version.

**Comment by syohex** [comment] 2015-07-14 14:48
I can reproduce this issue with following code.

```bash
% go build test.go
% port installed | ./test.go
```

```go
package main

import (
	"fmt"
	"os"

	"github.com/nsf/termbox-go"
)

func main() {
	err := termbox.Init()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed: termbox.Init: ", err)
		os.Exit(1)
	}
	defer termbox.Close()

	eventCh := make(chan termbox.Event)
	go func() {
		for {
			eventCh <- termbox.PollEvent()
		}
	}()

	for {
		select {
		case ev := <-eventCh:
			if ev.Type == termbox.EventKey {
				switch {
				case ev.Key == termbox.KeyEsc:
					return
				case ev.Ch >= 'a' && ev.Ch <= 'z':
					fmt.Fprintln(os.Stderr, "Type: '", ev.Ch, "'")
				}
			}
		}
	}
}
```

`termbox-go` watches keyboard events via SIGIO of `/dev/tty`. But the process never receives SIGIO if its input is `port installed`. I should test with more simple example without termbox-go.

**Comment by syohex** [comment] 2015-07-14 15:18
I can also reproduce this issue by following code which is part of `termbox-go`. I suppose this is MacPorts(Tcl) issue or MacOSX(Kernel) issue.

```
% go build test2.go
% port installed | ./test2
```

```go
package main

import "C"

import (
	"log"
	"os"
	"os/signal"
	"runtime"
	"syscall"
	"time"
	"unsafe"
)

type syscall_Termios struct {
	Iflag     uint64
	Oflag     uint64
	Cflag     uint64
	Lflag     uint64
	Cc        [20]uint8
	Pad_cgo_0 [4]byte
	Ispeed    uint64
	Ospeed    uint64
}

const (
	syscall_IGNBRK = 0x1
	syscall_BRKINT = 0x2
	syscall_PARMRK = 0x8
	syscall_ISTRIP = 0x20
	syscall_INLCR  = 0x40
	syscall_IGNCR  = 0x80
	syscall_ICRNL  = 0x100
	syscall_IXON   = 0x200
	syiscall_OPOST = 0x1
	syscall_ECHO   = 0x8
	syscall_ECHONL = 0x10
	syscall_ICANON = 0x100
	syscall_ISIG   = 0x80
	syscall_IEXTEN = 0x400
	syscall_CSIZE  = 0x300
	syscall_PARENB = 0x1000
	syscall_CS8    = 0x300
	syscall_VMIN   = 0x10
	syscall_VTIME  = 0x11

	syscall_TCGETS = 0x40487413
	syscall_TCSETS = 0x80487414
)

func fcntl(fd int, cmd int, arg int) (val int, err error) {
	r, _, err := syscall.Syscall(syscall.SYS_FCNTL, uintptr(fd), uintptr(cmd), uintptr(arg))
	val = int(r)
	return
}

func tcsetattr(fd int, termios *syscall_Termios) {
	r, _, e := syscall.Syscall(syscall.SYS_IOCTL, uintptr(fd), uintptr(syscall_TCSETS), uintptr(unsafe.Pointer(termios)))
	if r != 0 {
		panic(os.NewSyscallError("SYS_IOCTL", e))
	}
}

func tcgetattr(fd int, termios *syscall_Termios) {
	r, _, e := syscall.Syscall(syscall.SYS_IOCTL, uintptr(fd), uintptr(syscall_TCGETS), uintptr(unsafe.Pointer(termios)))
	if r != 0 {
		panic(os.NewSyscallError("SYS_IOCTL", e))
	}
}

func main() {
	var (
		in        int
		err       error
		sigio     = make(chan os.Signal)
		orig_tios syscall_Termios
	)
	in, err = syscall.Open("/dev/tty", syscall.O_RDONLY, 0)
	if err != nil {
		panic(err)
	}

	signal.Notify(sigio, syscall.SIGIO)

	fcntl(in, syscall.F_SETFL, syscall.O_ASYNC|syscall.O_NONBLOCK)
	_, err = fcntl(in, syscall.F_SETOWN, syscall.Getpid())
	if runtime.GOOS != "darwin" && err != nil {
		panic(err)
	}

	tcgetattr(in, &orig_tios)
	tios := orig_tios
	tios.Iflag &^= syscall_BRKINT | syscall_IXON
	tios.Lflag &^= syscall_ECHO | syscall_ICANON |
		syscall_ISIG | syscall_IEXTEN
	tios.Cflag &^= syscall_CSIZE | syscall_PARENB
	tios.Cflag |= syscall_CS8
	tios.Cc[syscall_VMIN] = 1
	tios.Cc[syscall_VTIME] = 0

	tcsetattr(in, &tios)
	defer func() {
		tcsetattr(in, &orig_tios)
		syscall.Close(in)
	}()

	buf := make([]byte, 128)
	for {
		log.Println("Waiting on signal")
		select {
		case <-sigio:
			log.Println("Read..")
			n, err := syscall.Read(in, buf)
			log.Println("Received:", n, err)
			if err == syscall.EAGAIN || err == syscall.EWOULDBLOCK {
				break
			}
			if n > 0 {
				if buf[0] == 17 {
					return
				}
				log.Println("buf:", buf[:n])
			}
		case <-time.After(time.Second * 5):
			log.Println("Timed out")
			return
		}
	}
}
```

**Comment by syohex** [comment] 2015-07-14 23:18
I can reproduce this issue without go. I suppose this is MacPorts issue or MacOSX kernel(darwin) issue. This issue may be solved by re-designing `terminal-go` that do not use SIGIO for watching keyboard events but this is hard work because [percol](https://github.com/mooz/percol) does not raise this issue).
```
% cc 
% cc -std=c99 -o test test.c
% port installed | ./test
```

(I took following code from [Linux Programming Interface 63.3](http://www.amazon.co.jp/The-Linux-Programming-Interface-Handbook/dp/1593272200))
```c
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <stdbool.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/uio.h>
#include <unistd.h>
#include <fcntl.h>
#include <termios.h>

static volatile sig_atomic_t gotSigio = 0;

static void
sigioHandler(int sig)
{
	gotSigio = 1;
}

static int
ttySetCbreak(int fd, struct termios *prevTermios)
{
	struct termios t;

	if (tcgetattr(fd, &t) == -1)
		return -1;

	if (prevTermios != NULL)
		*prevTermios = t;

	t.c_lflag &= ~(ICANON | ECHO);
	t.c_lflag |= ISIG;

	t.c_iflag &= ~ICRNL;

	t.c_cc[VMIN] = 1;                   /* Character-at-a-time input */
	t.c_cc[VTIME] = 0;                  /* with blocking */

	if (tcsetattr(fd, TCSAFLUSH, &t) == -1)
		return -1;

	return 0;
}

int
main(int argc, char *argv[])
{
	int flags, j, cnt, fd;
	struct termios origTermios;
	char ch;
	struct sigaction sa;
	_Bool done;

	sigemptyset(&sa.sa_mask);
	sa.sa_flags = SA_RESTART;
	sa.sa_handler = sigioHandler;
	if (sigaction(SIGIO, &sa, NULL) == -1) {
		perror("sigaction(SIGIO)");
		exit(1);
	}

	fd = open("/dev/tty", O_RDONLY);
	if (fd == -1) {
		perror("open");
		exit(1);
	}

//	XXX fcntl(fd, F_SETOWN, pid) is failed on Darwin/MacOSX
//	if (fcntl(fd, F_SETOWN, getpid()) == -1) {
//		perror("fcntl(F_SETOWN)");
//		exit(1);
//	}

	flags = fcntl(fd, F_GETFL);
	if (fcntl(fd, F_SETFL, flags | O_ASYNC | O_NONBLOCK) == -1) {
		perror("fcntl(F_SETFL)");
		exit(1);
	}

	if (ttySetCbreak(fd, &origTermios) == -1) {
		perror("ttySetCbreak");
		exit(1);
	}

	for (done = false, cnt = 0; !done ; cnt++) {
		for (j = 0; j < 100000000; j++)
			continue;

		if (gotSigio) {

			while (read(fd, &ch, 1) > 0 && !done) {
				printf("cnt=%d; read %c\n", cnt, ch);
				done = ch == '#';
			}
			gotSigio = 0;
		}
	}

	if (tcsetattr(fd, TCSAFLUSH, &origTermios) == -1) {
		perror("tcsetattr");
		exit(1);
	}

	return 0;
}
```

**Comment by syohex** [comment] 2015-07-17 03:42
@cuyler This is not a `peco` issue as described above. It is necessary to re-design and re-implement `termbox-go` which does not use `SIGIO` for resolving this issue. I suppose SIGIO support of MacOSX kernel is insufficient. For example fcntl(F_SETOWN) returns error on MacOSX. It does not work same as Linux implementation yet(However SIGIO is not POSIX specification, so UNIX system like MacOSX does not have to implement it).

Please use [percol](https://github.com/mooz/percol) if you want to avoid this issue. I confirmed `port installed | percol` works well. `percol` uses Python curses library for keyboard input. So this issue may be resolved by replacing SIGIO with curses functions in termbox-go.

**Closed by syohex** 2015-07-17 03:42 UTC

**Comment by mattn** [comment] 2015-07-17 04:01
@syohex could you please file this issue on https://github.com/nsf/termbox-go ?

**Comment by syohex** [comment] 2015-07-17 04:09
I think this is similar to https://github.com/nsf/termbox-go/issues/88
